---
title: "TO628_0314"
author: "Helga Zhang"
date: "2024-03-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(caret)

### **Load and clean data**

```{r}
hr_data <- read.csv("hrdata.csv")
summary(hr_data)
str(hr_data)

hr_data$X <- NULL
hr_data$sales <- as.factor(hr_data$sales)
hr_data$salary <- as.factor(hr_data$salary)
```
### **Split data into test and train**

```{r}
train_ratio <- 0.7
set.seed(12345)
train_rows <- sample(1:nrow(hr_data), train_ratio*nrow(hr_data))

hr_train <- hr_data[train_rows, ]
hr_test <- hr_data[-train_rows, ]
```

### **Build model**

```{r}
simplemodel <- glm(left ~ ., data = hr_train, family = "binomial")
summary(simplemodel)

intmodel <- glm(left ~ . + satisfaction_level + last_evaluation, data = hr_train, family = "binomial")
summary(intmodel)

#need to delete sales column to do step model
```
### **Make predictions**

```{r}
#testpred <- predict(simplemodel, newdata = hr_test, type = "response")
#summary(testpred)

#predict(simplemodel, newdata = newcase, type = "response")
```

